# docker-compose.yaml
version: '3'

services:
  web:
    build: '.'
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
