"""empty message

Revision ID: ea37c701e122
Revises: a75237630b7a
Create Date: 2023-12-12 12:29:57.024479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea37c701e122'
down_revision = 'a75237630b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superhero_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['superhero_id'], ['superheros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourites_superhero_id'), ['superhero_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourites_superhero_id'))
        batch_op.drop_index(batch_op.f('ix_favourites_id'))

    op.drop_table('favourites')
    # ### end Alembic commands ###
